### ISSUE TITLE
[New Feature]: War実装

### ISSUE THREAD

**Issue by yziori** [Recursion-Group-C/card-game#13]
### 概要

Warを実装する。

### 目的

[設計](https://github.com/Recursion-Group-C/card-game/wiki/%E8%A8%AD%E8%A8%88)に従い、Warの一連の流れを実装する。

### 提案内容

UI等は仮組みで進める。後日すり合わせ

**Comment by y0uk1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [13[New Feature]: War実装](https://trello.com/c/I1TO7y9e/61-13new-feature-war%E5%AE%9F%E8%A3%85)

**Comment by y0uk1** [comment]
[このフォルダ構成](https://github.com/spmuck/Blackjack/tree/master/src)を真似し用しようと思います。[Factory Methodというデザインパターン](https://qiita.com/shoheiyokoyama/items/d752834a6a2e208b90ca)を採用しているようです。
[gamesフォルダ](https://github.com/Recursion-Group-C/card-game/tree/develop/games)にwarフォルダを作成して、その配下でbindings, constants, models, scenes, utilityフォルダを作る形になります。modelsは、common/Factories配下の各クラスを継承する形で、Player class, Table classを作成する形を想定しています。
他のゲームに共通で使えそうなものは、gamesフォルダのcommonフォルダ配下に適宜追加していただいて構いません。
