### ISSUE TITLE
[Bug]: Blackjack Bug対応（勝敗がついた際の結果表示がされない）

### ISSUE THREAD

**Issue by ghost** [Recursion-Group-C/card-game#23]
### どんな不具合が出る？

# 1 勝敗がついた際の結果表示がされない現象が起きている。
![スクリーンショット 2023-04-08 11 10 41](https://user-images.githubusercontent.com/101037787/230698760-c98d6e0f-1ae0-42f6-9026-5851da131d3d.png)

### どんな動作を期待していた？

# 1
勝敗がついた際、まん中あたりに黄色の文字で「WIN」等の結果が表示されるようにしたい。

### 不具合の再現方法

# 1
BUSTする、またはSurrender以外で起こる。

### 原因

# 1
DoubleとSurrenderを実装してから起きた。
=> 原因は不明(endHand()内で起きている可能性大)

### 修正案

# 1
endHand()内のロジックで結果表示位置や文字の大きさ等を変更すると治るのでは？

**Comment by y0uk1** [comment]
@daitenn 
issue1つにバグ1つでお願いします。（このissueを2つに分割してください。）
そして、issueのタイトルをもう少し詳しくしてください。

**Comment by y0uk1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #23: [Bug]: Blackjack Bug対応（勝敗がついた際の結果表示がされない）](https://trello.com/c/mhWDNox1/68-issue-23-bug-blackjack-bug%E5%AF%BE%E5%BF%9C%EF%BC%88%E5%8B%9D%E6%95%97%E3%81%8C%E3%81%A4%E3%81%84%E3%81%9F%E9%9A%9B%E3%81%AE%E7%B5%90%E6%9E%9C%E8%A1%A8%E7%A4%BA%E3%81%8C%E3%81%95%E3%82%8C%E3%81%AA%E3%81%84%EF%BC%89)

**Comment by y0uk1** [comment]
#41 で対応
