### ISSUE TITLE
[Bug]: BlackjackのBag対応（ゲームに勝ってもお金が増えない。）

### ISSUE THREAD

**Issue by ghost** [Recursion-Group-C/card-game#26]
### どんな不具合が出る？

ゲームに勝ってもお金が増えない。

### どんな動作を期待していた？

ゲームに勝った際に、その賭けた金額分増える。

### 不具合の再現方法

どのコマンドを打っても可能。

### 原因

不明

### 修正案

不明

**Comment by y0uk1** [comment]
#41 で対応
