### ISSUE TITLE
[New Feature]: ルール説明を追加する

### ISSUE THREAD

**Issue by ghost** [Recursion-Group-C/card-game#53]
### 概要

ルールページを作成する。

### 目的

[設計](https://github.com/Recursion-Group-C/card-game/wiki/%E8%A8%AD%E8%A8%88)に従い、ルールページを作成する。

### 提案内容

ホームページにルール説明のボタンを追加する。そこからルールページに遷移する方法をとる。

### タスク

No response

**Comment by y0uk1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #53: [New Feature]: ルール説明を追加する](https://trello.com/c/aiur8ob6/96-issue-53-new-feature-%E3%83%AB%E3%83%BC%E3%83%AB%E8%AA%AC%E6%98%8E%E3%82%92%E8%BF%BD%E5%8A%A0%E3%81%99%E3%82%8B)
