### ISSUE TITLE
[New Feature]: BetSceneの背景画像追加

### ISSUE THREAD

**Issue by yziori** [Recursion-Group-C/card-game#57]
### 概要

BetSceneの背景画像を追加する。

### 目的

背景画像の追加

### 提案内容

いくつか候補画像を追加します。

**Comment by yziori** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #58: feat: 🍱 #57 背景用画像を追加](https://trello.com/c/nizaClJr/101-issue-58-feat-%F0%9F%8D%B1-57-%E8%83%8C%E6%99%AF%E7%94%A8%E7%94%BB%E5%83%8F%E3%82%92%E8%BF%BD%E5%8A%A0)

**Comment by y0uk1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #57: [New Feature]: BetSceneの背景画像追加](https://trello.com/c/c3B6P4Uk/100-issue-57-new-feature-betscene%E3%81%AE%E8%83%8C%E6%99%AF%E7%94%BB%E5%83%8F%E8%BF%BD%E5%8A%A0)
